-- MySQL Script generated by MySQL Workbench
-- Sun Dec 13 21:22:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inglesapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inglesapp` ;

-- -----------------------------------------------------
-- Schema inglesapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inglesapp` DEFAULT CHARACTER SET utf8 ;
USE `inglesapp` ;

-- -----------------------------------------------------
-- Table `inglesapp`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inglesapp`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `inglesapp`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nomeCargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inglesapp`.`Cadastrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inglesapp`.`Cadastrado` ;

CREATE TABLE IF NOT EXISTS `inglesapp`.`Cadastrado` (
  `idCadastrado` INT NOT NULL,
  `nomeCompleto` VARCHAR(45) NULL,
  `nomeUsuario` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` BIGINT(11) NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idCadastrado`),
  INDEX `fk_Cadastrado_Cargo_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Cadastrado_Cargo`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `inglesapp`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inglesapp`.`TemaAula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inglesapp`.`TemaAula` ;

CREATE TABLE IF NOT EXISTS `inglesapp`.`TemaAula` (
  `idTemaAula` INT NOT NULL,
  `tema` VARCHAR(45) NULL,
  PRIMARY KEY (`idTemaAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inglesapp`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inglesapp`.`Aula` ;

CREATE TABLE IF NOT EXISTS `inglesapp`.`Aula` (
  `idAula` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `conteudo` VARCHAR(5000) NULL,
  `Cadastrado_idCadastrado` INT NOT NULL,
  `TemaAula_idTemaAula` INT NOT NULL,
  PRIMARY KEY (`idAula`),
  INDEX `fk_Aula_Cadastrado1_idx` (`Cadastrado_idCadastrado` ASC),
  INDEX `fk_Aula_TemaAula1_idx` (`TemaAula_idTemaAula` ASC),
  CONSTRAINT `fk_Aula_Cadastrado1`
    FOREIGN KEY (`Cadastrado_idCadastrado`)
    REFERENCES `inglesapp`.`Cadastrado` (`idCadastrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aula_TemaAula1`
    FOREIGN KEY (`TemaAula_idTemaAula`)
    REFERENCES `inglesapp`.`TemaAula` (`idTemaAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
